### ISSUE TITLE
ARBITRUM Curve RenBTC-wBTC 

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-strategies#11]
# Strategy Review

Release: 
https://github.com/GalloDaSballo/arbitrum-ren-wbtc-curve-strat/tree/b0.2

Reviews:

### Description

Deposit renBTC-wBTC cLP
Stake them in gauge
harvest curve
50% sent to badgerTree
Rest autocompounded -> CRV -> wBTC -> more cLP

## Due Diligence Document  (Link, but could also just be a .md file in repo)
Same as from Mainnet

## Deployed Contract (If present)
Waiting for informal acknowledgment by Ayush and Dapp

## Review By
* Ongoing: 
  [] @shuklaayush 
  [] @dapp-whisperer 
  
* Completed:

## Review by Security Board
Sent to Board

## Test Checks (screen shot of all test passing)
Tests are passing screenshot below (updated for second release)
<img width="961" alt="Screenshot 2021-09-16 at 15 14 04" src="https://user-images.githubusercontent.com/13383782/133618617-195928e9-3bf9-4883-ab74-b063be6ccd4a.png">

**Comment by GalloDaSballo** [comment]
Deployment in an hour or two

**Comment by dapp-whisperer** [comment]
Signing off for live test
- Alex and I have discussed all points of consideration
- Liquidity confirmed on sushi path

**Comment by GalloDaSballo** [comment]
Issue with Liquidity on the CRV -> ETH side (no liquidity)
<img width="915" alt="Screenshot 2021-09-16 at 14 59 53" src="https://user-images.githubusercontent.com/13383782/133616492-dfca6bd4-4a69-4d1b-bc8e-02136934c13e.png">

Low but acceptable on the wBTC -> ETH Side
<img width="812" alt="Screenshot 2021-09-16 at 15 00 04" src="https://user-images.githubusercontent.com/13383782/133616518-67afb586-43ab-4059-ae7e-e7379628a63b.png">

**Comment by GalloDaSballo** [comment]
Update:
Updated strat (new release above) to reinvest harvested funds

**Comment by GalloDaSballo** [comment]
CRV -> WETH liquidity being seeded rn

**Comment by shuklaayush** [comment]
### Comments
- Polygon --> Arbitrum
https://github.com/GalloDaSballo/arbitrum-ren-wbtc-curve-strat/blob/b0.2/contracts/MyStrategy.sol#L120-L122
![image](https://user-images.githubusercontent.com/27727946/133627728-38fc254d-b99b-470c-8fa6-106148c9c7e0.png)

- Contract name can also be changed from MyStrategy --> CurveStrategy or something

- `lpComponent` is redundant and can be removed

- Harvest function deposits funds after claiming and swapping, so strategy should never have any extra want. I guess this means that `isTendable` should always return false instead of true. Might be better to just let the condition be `balanceOfWant() > 0`

- Ideally, `withdrawSome` should first check `balanceOfWant` but I guess this works since the strategy should never have extra want

- We can add a slippage check to `add_liquidity` since Curve has a `get_virtual_price` function which is basically the exchange rate

- Might want to update to SettV4 for future-proofing

---

Strategy takes Curve LP tokens and stakes them on the rewards gauge.

During harvest, it 
1. Claims the rewards and forwards 50% of them to badger tree (after processing fees)
2. Swaps remaining rewards for WBTC through Sushi CRV --> WETH --> WBTC path, and uses them to add liquidity to the Curve ren pool
3. Deposits the want gained to compound strategy balance

---

CRV-WETH liquidity seems sufficient for now
https://arbiscan.io/address/0xbe3b9c3700171183b2b3f827d8833212d0197a96
![image](https://user-images.githubusercontent.com/27727946/133636353-7545ccb3-f3c2-46ab-9500-6a51f54d9391.png)

---
Tests are passing and LGTM. Most of the comments are minor and strategy logic looks fine 

![image](https://user-images.githubusercontent.com/27727946/133635331-caf313cf-e286-4054-8fe3-fdc3e2b14fde.png)

**Comment by GalloDaSballo** [comment]
Somehow we don't have addresses here

**Comment by GalloDaSballo** [comment]
Addresses:
Vault: 0xBA418CDdd91111F5c1D1Ac2777Fa8CEa28D71843

Strat Logic:
0x86146833ba27d37103eC70341A80f3fF51D8059A

Strat proxy:
0x4C5d19Da5EaeC298B79879a5f7481bEDE055F4F8

**Comment by GalloDaSballo** [comment]
Upgrade with new code as well as test to check that upgrade will preserve functionality:
https://github.com/GalloDaSballo/arbitrum-ren-wbtc-curve-strat/tree/Upgrade.1

**Comment by GalloDaSballo** [comment]
Note:
After upgrading, have governance call: `setSwaprAllowance` to ensure new router has allowance
