### ISSUE TITLE
[FTM] Solid Strategy

### ISSUE THREAD

**Issue by GalloDaSballo** [Badger-Finance/badger-strategies#37]
# Strategy Review
VETO BASED REVIEW
Find a reason to stop and we'll stop immediately

Gauge Staking -> Emit SOLID

### Description
Gauge Staking -> Emit SOLID

### Code Link 
https://github.com/shuklaayush/ftm-testnet-solidly/blob/v0.1.0/contracts/MyStrategy.sol

## Due Diligence Document  (Link, but could also just be a .md file in repo)
This document evaluates the protocols that are interacted with as strategy positions.

## Review By
* Ongoing: 
[] Alex
[] Tabish
[] Ayush
[] Dapp
[] Saj

## Review by Security Board
* Not started / ongoing / completed

**Comment by shuklaayush** [comment]
Basic strategy code:
https://github.com/shuklaayush/ftm-testnet-solidly/blob/v0.1.0/contracts/MyStrategy.sol

There's also this factory contract for easier deployments but it's untested because of verification/rpc issues:
https://github.com/shuklaayush/ftm-testnet-solidly/blob/v0.1.0/contracts/BadgerSolidlyFactory.sol

**Comment by Tritium-VLK** [comment]
Performance 15%
