### ISSUE TITLE
[AURA] Bpt staking optimizers (Badger/Wbtc, BB-A-USD)

### ISSUE THREAD

**Issue by shuklaayush** [Badger-Finance/badger-strategies#66]
# Strategy Review

### Description
Stake bpts on aura to get rewards
- bal -> emitted as bauraBal
- aura -> emitted as graviAura

### Code Link 
https://github.com/shuklaayush/strategy-aura-staking/tree/v0.0.3

## Due Diligence Document  (Link, but could also just be a .md file in repo)
Aura
Aura Report yet to be released, from my own knowledge meaningful bugs where mitigated:
https://code4rena.com/reports

Balancer:
https://docs.balancer.fi/security/audits

## Review By
* Ongoing: 
* Completed:

## Review by Security Board
* Not started / ongoing / completed

## Test Checks (screen shot of all test passing)
<img width="899" alt="image" src="https://user-images.githubusercontent.com/27727946/176475857-ce88efc1-e132-47b8-b637-b796eedb7a79.png">

## Launch Checklist

**BADGER/WBTC** 
- [x] Strategy development - Strategist
- [x] Strategy fork testing - Strategist/QA Pod
- [x] Strategy review - Solidity Pod/QA pod
- [x] Contracts deployment and initialization - Strategist/QA Pod
- [x] Addition of vault to the Badger Registry - Strategist/QA Pod
- [x] Wire-up of contracts to the UI (On-chain with RegistryV2) - UI/API pod
- [x] Guestlist deployment and setup (If guarded launch) - Strategist/QA Pod
- [x] Test deposit through the UI - Strategist/QA Pod
- [x] Production tests of operational functions (Earn, Harvest, Tend) - Strategist/QA Pod
- [x] Add vault/strategy addresses to the keeper bot - Emissions Pod
- [x] Test a rewards claim (If new reward token is emitted) - Strategist/QA Pod
- [x] APY and balance on UI verification - Strategist/QA Pod
- [x] User Guide and Strategy diagram - Comms pod
- [x] Contract addresses additions to Docs - Comms/QA pod
- [x] Contracts delegation - Strategist/QA Pod
- [x] Contracts' Production parameters and delegation verification - Solidity/QA pod
- [x] Production launch - UI/API Pod
- [x] Announcements - Comms pod

**BB-A-USD** 
- [x] Strategy development - Strategist
- [x] Strategy fork testing - Strategist/QA Pod
- [x] Strategy review - Solidity Pod/QA pod
- [x] Contracts deployment and initialization - Strategist/QA Pod
- [x] Addition of vault to the Badger Registry - Strategist/QA Pod
- [x] Wire-up of contracts to the UI (On-chain with RegistryV2) - UI/API pod
- [x] Guestlist deployment and setup (If guarded launch) - Strategist/QA Pod
- [x] Test deposit through the UI - Strategist/QA Pod
- [x] Production tests of operational functions (Earn, Harvest, Tend) - Strategist/QA Pod
- [x] Add vault/strategy addresses to the keeper bot - Emissions Pod
- [x] Test a rewards claim (If new reward token is emitted) - Strategist/QA Pod
- [x] APY and balance on UI verification - Strategist/QA Pod
- [x] User Guide and Strategy diagram - Comms pod
- [x] Contract addresses additions to Docs - Comms/QA pod
- [x] Contracts delegation - Strategist/QA Pod
- [x] Contracts' Production parameters and delegation verification - Solidity/QA pod
- [x] Production launch - UI/API Pod
- [x] Announcements - Comms pod

**Comment by GalloDaSballo** [comment]
Comment:
<img width="729" alt="Screenshot 2022-06-29 at 17 37 37" src="https://user-images.githubusercontent.com/13383782/176477759-9cfe0b9e-2166-490e-a827-4a2fc5fd0f70.png">

`state_setup` can be written as a fixture so you don't need to call it at beginning of each test

Request:
Would like a basic test proving that pool is valid for want

Question:
https://github.com/shuklaayush/strategy-aura-staking/blob/edcd4f1ca6ecf845540d1d2fa2c08e0179e81bfe/contracts/StrategyAuraStaking.sol#L89

In which situation would this change be needed?


Question:
https://github.com/shuklaayush/strategy-aura-staking/blob/edcd4f1ca6ecf845540d1d2fa2c08e0179e81bfe/contracts/StrategyAuraStaking.sol#L179-L180

```solidity
        // BB_A_USD  --> Left in strategy to be sweeped later

```
What does this mean?

**Comment by GalloDaSballo** [comment]
<img width="963" alt="Screenshot 2022-06-29 at 18 02 31" src="https://user-images.githubusercontent.com/13383782/176482873-f686c90d-496b-4712-b132-97207c7f66c8.png">

**Comment by rayeaster** [comment]
https://github.com/shuklaayush/strategy-aura-staking/blob/v0.0.2/contracts/StrategyAuraStaking.sol#L86 better to use `safeApprove()` instead of `approve()`?

**Comment by shuklaayush** [comment]
> https://github.com/shuklaayush/strategy-aura-staking/blob/v0.0.2/contracts/StrategyAuraStaking.sol#L86 better to use safeApprove() instead of approve()?

I think it should be fine since we're only doing it once. I didn't want to write `IERC20Upgradeable(address(AURA)).safeApprove(...)`

**Comment by rayeaster** [comment]
https://github.com/shuklaayush/strategy-aura-staking/blob/v0.0.2/contracts/StrategyAuraStaking.sol#L234 do we need any oracle here for `BALETH BPT` -> `AURABAL` swap. it seems to me this directly applies slippage calculation without price conversion? `BALETH BPT` is 1:1 to `AURABAL`?

**Comment by shuklaayush** [comment]
> https://github.com/shuklaayush/strategy-aura-staking/blob/v0.0.2/contracts/StrategyAuraStaking.sol#L234 do we need any oracle here for BALETH BPT -> AURABAL swap. it seems to me this directly applies slippage calculation without price conversion? BALETH BPT is 1:1 to AURABAL?

It should ideally be 1:1 but I think it's off-peg right now in our favour. I don't think we necessarily need an oracle since it usually won't be off-peg in the other direction (because there's an arbitrage opportunity if it is). And we usually harvest using flashbots so it shouldn't be off-peg due to sandwiching

**Comment by sajanrajdev** [comment]
## Review

### Description
Generic staking optimizer strategy for the Aura ecosystem. It is initialized with an Aura pool id which is used to fetch from the booster all of the necessary contracts  corresponding to the Balancer BPT. That is that want (lptoken) and the base rewards contract (crvRewards).

The strategy receives BAL, AURA and BB_A_USD as rewards. It compounds all of the BAL into bauraBAL and emits it, compounds all of the AURA into graviAURA and emits it and does't process the BB_A_USD (it receives a very insignificant amount that wouldn't be cost efficient to process. These can be sweeped for manual processing).

Additionally, a factory contract was developed to allow for a quicker, more efficient and decentralized way to launch vaults that use this strategy.

### Features
- Includes flag to allow for rewards claiming upon `withdrawAll()`  (**NOTE**:  `_withdrawAll` can only be called by the vault and it only handled the `want` token. If rewards are claimed when withdrawing for a broken harvest for instance, AURA and BAL won't be processed and stuck on the strat as they are protected tokens. The broken strat will need to be upgraded to remove the protection or to fix harvest in order for these rewards to be rescued. It is still handy to claim all rewards when exiting a position fully - AURA rewards are calculated at claim time based on the `totalSupply` and, if they are left unclaimed for a long time, the claimable amount may be reduced considerably).
- The claimable AURA amount is estiamated by mimicking the minting logic - same logic as CVX - this function is kept public so could be leveraged as needed externally. LG. 
- Includes a check within `setPid` to ensure that all want tokens are un-staked before migrating to a different pool. It also checks that the new PID must point to the same underlying pool. A flow for migration would be: `withdraw all to vault + setPid + earn()` - LGTM
- Sets default slippage check for ETHBAL_BPT to AuraBAL to 5%
- Based on the findings from the review of [bauraBAL](https://github.com/Badger-Finance/badger-strategies/issues/58#issuecomment-1169119832), the chose path for processing rewards LGTM ( In the future, once graviAURA pools are stablished, we could explore swapping AURA for graviAURA it turns out to be more efficient/optimal).

### Notes
- All hardcoded addresses LGTM
- Confirmed `BAL_ETH_POOL_ID` and `AURABAL_BALETH_BPT_POOL_ID` from the Balancer Vault:
![image](https://user-images.githubusercontent.com/25463788/176729917-1dda00fb-f82c-4660-a886-1e923acee227.png)
![image](https://user-images.githubusercontent.com/25463788/176730030-a9d8c01c-bf87-47ff-af16-12c4f33d5956.png)
- I don't think it is a big deal to let the BB_A_USD sit until there is enough to process separately but, as an alternative, we could handle as we handle 3Crv on the Convex Staking Optimizer: Have a threshold of the minimum amount required to be accumulated on the strat and once this threshold is met, the harvest function could swap for either of the other assets (in that case, CRV). [See reference](https://github.com/Badger-Finance/strategy-convex-staking-optimizer/blob/e9606936a98ab7c50dd22919b5be898b51ccf730/contracts/StrategyConvexStakingOptimizer.sol#L431-L444)

### Testing
Resolver confirms that there is no autocompound and that the expected amounts of bauraBAL and graviAURA are emitted to the Tree upon harvest. Also, it confirms that performance fees are processed properly.

Custom tests were added to ensure that the pid that the strat is initialized with corresponds to the token that the vault is initialized with. Also, ensures that the checks of the `setPid` function work as expected.

**NOTE**: Tests are missing for the factory contract, I suggest that we review the factory on a separate issue once tests are introduced. Not a blocker for the strategy if it will be deployed directly from source.

All tests are passing and LGTM:
![image](https://user-images.githubusercontent.com/25463788/176731751-b7141e0c-903e-45e4-ba0a-8f8cb70ef7df.png)

LGTM

**Comment by GalloDaSballo** [comment]
Have Reviewed Relase 3: https://github.com/shuklaayush/strategy-aura-staking/releases/tag/v0.0.3
LGTM, would like to see a private harvest

**Comment by shuklaayush** [comment]
### Deployment

Strategy logic: [0x83897F8892244b406346cC3811712275e2005694](https://etherscan.io/address/0x83897F8892244b406346cC3811712275e2005694)

#### bbb-a-usd
Vault proxy: [0x06D756861De0724FAd5B5636124e0f252d3C1404](https://etherscan.io/address/0x06D756861De0724FAd5B5636124e0f252d3C1404)

Strategy proxy: [0x2eDc46AC0eE850081e14a6E6cF09d69A29D61563](https://etherscan.io/address/0x2eDc46AC0eE850081e14a6E6cF09d69A29D61563)

**Comment by sajanrajdev** [comment]
As confirmed by Aura devs, regular BPT staking won't be receiving any BB-A-USD so we don't need to prepare to process it, hence, no changes needed there.

Release v0.0.3 modifies the tests setup to run with BB-A-USD as want. Also changed the name of the strat to a more generalized one.

Tests continue to pass, an example of a harvest shows that the strat will process rewards properly without leaving dust behind:
![image](https://user-images.githubusercontent.com/25463788/177373261-e15fb958-b52e-4593-8ca3-a0a3bdefd08d.png)
![image](https://user-images.githubusercontent.com/25463788/177373312-63bd569a-3002-4f66-860c-84a695671cd0.png)

Changes LGTM

**Comment by sajanrajdev** [comment]
## Deployment review

### Vault
Token: bb-a-usd 
Strategy: [0x2edc46ac0ee850081e14a6e6cf09d69a29d61563](https://etherscan.io/address/0x2edc46ac0ee850081e14a6e6cf09d69a29d61563)

**Actors:**
- Governance: deployer to be delegated
- Guardian: warroom
- keeper: ACL
- Strategist: TechOps
- Treasury: Trops

LGTM

No guestlist set yet

**Fees**:
- Withdrawal Fee: 0.1%
- Perf: 20%
- Mgmt: 0%

@shuklaayush, as per discussion, should be adapted to:
![image](https://user-images.githubusercontent.com/25463788/177380928-737d0523-852c-4908-aa54-531b1e72cf11.png)

### Strategy:

Logic matches latest release: https://www.diffchecker.com/mBqHu5r3 - LGTM
Slippage protection: 5%
PID: 4 (Confirmed pool on booster)
Want: bb-a-usd
Vault: [0x06d756861de0724fad5b5636124e0f252d3c1404](https://etherscan.io/address/0x06d756861de0724fad5b5636124e0f252d3c1404)

Other than the fees, deployments LGTM

**Comment by shuklaayush** [comment]
Updated fees on bbb-a-usd
- New withdrawal fee: 0%
- New performance fee governance: 10%

https://etherscan.io/tx/0x102f1b81d4ca86620bca80fae80d2b04155821c3aaa0e1b66b894f92ab66bd79
https://etherscan.io/tx/0x09980dad8e511dae45602c0cf036fe31f8a6a396e3f89f35268a5d574c0a15ff

**Comment by shuklaayush** [comment]
### Deployment

#### 80badger-20wbtc
Vault proxy: [0x63ad745506BD6a3E57F764409A47ed004BEc40b1](https://etherscan.io/address/0x63ad745506BD6a3E57F764409A47ed004BEc40b1)

Strategy proxy: [0xe43857fE16D18b6633A663389934d6c64D5E81FD](https://etherscan.io/address/0xe43857fE16D18b6633A663389934d6c64D5E81FD)

**Comment by Tritium-VLK** [comment]
Confirming fees from contract:

0% management
20% performance fee
0.1% withdraw
0% strategist

**Comment by shuklaayush** [comment]
## Guestlists
### bbb-a-usd
[0x499c3d66355685990a790e0ee5f43e4bce3dd1a4](https://etherscan.io/address/0x499c3d66355685990a790e0ee5f43e4bce3dd1a4)

No user cap
Total cap: 1e24 = 1mn = $1mn (assuming price ~$1)

### 80badger-20wbtc
[0x38261fdCA5CE38d49a44507BD53D17C12dC7414b](https://etherscan.io/address/0x38261fdCA5CE38d49a44507BD53D17C12dC7414b)

No user cap
Total cap at 69k based on following calculation

Current prices:
- Badger: $3.05
- Wbtc: $19706.33

80badger-20wbtc pool:
- Invariant: 243325.47
- Total supply: 485945.66

Price of bpt can be calculated as

$$
\begin{align*}
p_{bpt} &= \frac{Invariant}{TotalSupply}\cdot \left(\frac{p_1}{w_1}\right)^{w_1} \cdot \left(\frac{p_2}{w_2}\right)^{w_2}\\
              &= \frac{243325.47}{485945.66}\cdot \left(\frac{3.05}{0.8}\right)^{0.8} \cdot \left(\frac{19706.33}{0.2}\right)^{0.2}\\
              &\approx $14.56
\end{align*}
$$

69k bpt ~ $1mn

**Comment by sajanrajdev** [comment]
- Guestlists caps LGTM and their guestRoots are set to 0x0 as expected - LGTM
- Confirmed that guestlists were added to the vaults contracts

As per our discussion @shuklaayush, we should delegate guestLists to TechOps from now and on (unless someone has a different opinion). I will create a ticket on the `badger-multisig` repo to introduce guestlist handling functions to the GreatApeSafe library for quick calls management without repetitive scripting.

**Comment by rayeaster** [comment]
## Strategy Review

- LTGM for `deposit`, `withdrawAll`, `withdrawSome`, `harvest`
- Tests passed for `v0.0.3` branch

**Comment by sajanrajdev** [comment]
Manual harvests:
bb-a-USD harvest:
https://etherscan.io/tx/0x504d225f7010ebd78a01739f8113baea36539856f012f512f3142d0711af1c9a

80BADGER/20WBTC: https://etherscan.io/tx/0xd63af8b14f18958cfccf59eea94c4dfdaa2409aee348448bd70bf6f17d9897a7

**Comment by GalloDaSballo** [comment]
Live on Tuesday Guarded

**Comment by sajanrajdev** [comment]
## Launch Checklist

**BADGER/WBTC** 
- [x] Strategy development - Strategist
- [x] Strategy fork testing - Strategist/QA Pod
- [x] Strategy review - Solidity Pod/QA pod
- [x] Contracts deployment and initialization - Strategist/QA Pod
- [x] Addition of vault to the Badger Registry - Strategist/QA Pod
- [x] Wire-up of contracts to the UI (On-chain with RegistryV2) - UI/API pod
- [x] Guestlist deployment and setup (If guarded launch) - Strategist/QA Pod
- [x] Test deposit through the UI - Strategist/QA Pod
- [x] Production tests of operational functions (Earn, Harvest, Tend) - Strategist/QA Pod
- [x] Add vault/strategy addresses to the keeper bot - Emissions Pod
- [x] Test a rewards claim (If new reward token is emitted) - Strategist/QA Pod
- [x] APY and balance on UI verification - Strategist/QA Pod
- [x] User Guide and Strategy diagram - Comms pod
- [x] Contract addresses additions to Docs - Comms/QA pod
- [x] Contracts delegation - Strategist/QA Pod
- [x] Contracts' Production parameters and delegation verification - Solidity/QA pod
- [x] Production launch - UI/API Pod
- [x] Announcements - Comms pod

**BB-A-USD** 
- [x] Strategy development - Strategist
- [x] Strategy fork testing - Strategist/QA Pod
- [x] Strategy review - Solidity Pod/QA pod
- [x] Contracts deployment and initialization - Strategist/QA Pod
- [x] Addition of vault to the Badger Registry - Strategist/QA Pod
- [x] Wire-up of contracts to the UI (On-chain with RegistryV2) - UI/API pod
- [x] Guestlist deployment and setup (If guarded launch) - Strategist/QA Pod
- [x] Test deposit through the UI - Strategist/QA Pod
- [x] Production tests of operational functions (Earn, Harvest, Tend) - Strategist/QA Pod
- [x] Add vault/strategy addresses to the keeper bot - Emissions Pod
- [x] Test a rewards claim (If new reward token is emitted) - Strategist/QA Pod
- [x] APY and balance on UI verification - Strategist/QA Pod
- [x] User Guide and Strategy diagram - Comms pod
- [x] Contract addresses additions to Docs - Comms/QA pod
- [x] Contracts delegation - Strategist/QA Pod
- [x] Contracts' Production parameters and delegation verification - Solidity/QA pod
- [x] Production launch - UI/API Pod
- [x] Announcements - Comms pod

**Comment by GalloDaSballo** [comment]
Closing as successful
